//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Category
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Category()
    {
        this.Purchases = new HashSet<Purchase>();
    }

    public int CId { get; set; }
    public string CName { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Purchase> Purchases { get; set; }
}

public partial class Purchase
{
    public int PurId { get; set; }
    public string ProductID { get; set; }
    public string PName { get; set; }
    public Nullable<decimal> Price { get; set; }
    public Nullable<int> Quantity { get; set; }
    public Nullable<System.DateTime> DOP { get; set; }
    public string Picture { get; set; }
    public Nullable<int> CId { get; set; }

    public virtual Category Category { get; set; }
}

public partial class Register
{
    public int RegId { get; set; }
    public string RUName { get; set; }
    public string RUEmail { get; set; }
    public string RUPassword { get; set; }
    public string RUConfirmPassword { get; set; }
}

public partial class tblRole
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tblRole()
    {
        this.tblUsers = new HashSet<tblUser>();
    }

    public int rId { get; set; }
    public string rName { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<tblUser> tblUsers { get; set; }
}

public partial class tblUser
{
    public int uId { get; set; }
    public string uEmail { get; set; }
    public string uName { get; set; }
    public string uPass { get; set; }
    public Nullable<int> rId { get; set; }

    public virtual tblRole tblRole { get; set; }
}
