//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class ProjectDatabaseEntities : DbContext
{
    public ProjectDatabaseEntities()
        : base("name=ProjectDatabaseEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<Category> Categories { get; set; }
    public virtual DbSet<Purchase> Purchases { get; set; }
    public virtual DbSet<Register> Registers { get; set; }
    public virtual DbSet<tblRole> tblRoles { get; set; }
    public virtual DbSet<tblUser> tblUsers { get; set; }
}
